### ISSUE TITLE
webApiPermissionRequests entry 

### ISSUE THREAD

**Issue by pradiptanayak2007** [vman/ServiceScopeTestBench#1]
Thanks for nice article. I tried to deploy the solution. But found webApiPermissionRequests entry is missing in solution config file. Do we need that entry or not. 

Not sure if we have to mention in each solution as it is approved for tenant.I heard from 1.9.0 they are going to clear this confusion and start providing per solution permission management ?

But for safe side I have added and the solution work fine :). Many thanks as I was trying this looking from many sites but can't get a good solution which work perfectly.

**Comment by vman** [comment]
Hi @pradiptanayak2007, Glad that the solution worked for you! 

I just tried creating a package and deploying to the app catalog and did not get the error you mentioned about `webApiPermissionRequests `

Did you get this error without making any changes to the existing code?

**Comment by pradiptanayak2007** [comment]
thanks for the reply. Actually I did not get any issue with your code. But what I realize if you are deploying any solution for first time and you don't have required permission then you have to mention those **Scope** (Mail.Read, User.ReadBasic.All etc) in the config file in webApiPermissionRequests Node else you will get access denied.

![API Management](https://user-images.githubusercontent.com/12250182/57449563-e334ac00-7279-11e9-8d8c-c57a85182f9f.JPG)

**Comment by vman** [comment]
Aah yes, that is definitely needed if you are making a call to a Graph endpoint which needs more permissions than `user_impersonation`

By default, the SPFx Azure AD App Registration has the `user_impersonation` permission granted but if you need anything else, you have to request it in the `webApiPermissionRequests` object and grant it from the tenant admin. 

See this page for more details: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#access-to-the-microsoft-graph

**Comment by pradiptanayak2007** [comment]
Yep..thanks now things are clear ...
